# Generated by Django 5.1.6 on 2025-02-28 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('estatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipoBoleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('fechaInicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('localidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('localidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='boletos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('eventos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.eventos')),
                ('tipo_boleto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.tipoboleto')),
            ],
        ),
    ]
