# Generated by Django 5.1.6 on 2025-02-28 03:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='imagen_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
