# Generated by Django 5.1.6 on 2025-03-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_eventos_imagen_url_alter_eventos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='fechaInicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='fechafin',
            field=models.DateTimeField(),
        ),
    ]
