# Generated by Django 5.1.6 on 2025-03-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0003_alter_eventos_fechainicio_alter_eventos_fechafin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='descripcion',
            field=models.CharField(default='No hay descripción', max_length=500),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='imagen_url',
            field=models.CharField(default='https://i.pinimg.com/170x/56/6a/8b/566a8b03ee78dd47250c559e26906df9.jpg', max_length=500),
        ),
    ]
