# Generated by Django 5.1.6 on 2025-03-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0004_alter_eventos_descripcion_alter_eventos_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='descripcion',
            field=models.CharField(blank=True, default='No hay descripción', max_length=500, null=True),
        ),
    ]
