# Generated by Django 5.1.6 on 2025-03-05 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0005_alter_eventos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
