# Generated by Django 5.1.6 on 2025-03-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0007_alter_productos_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='created_at',
        ),
    ]
