# Generated by Django 5.1.6 on 2025-03-05 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0008_remove_productos_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
