# Generated by Django 5.1.6 on 2025-03-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0009_productos_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='imagen_url',
            field=models.CharField(default='https://img.freepik.com/vector-gratis/carnaval-brasileno-plano-creativo_23-2148404612.jpg?t=st=1741162794~exp=1741166394~hmac=01fa8f924797fe3952a086af7d70843819d9594470aa83abb3f2c20081f18117&w=900', max_length=500),
        ),
    ]
